global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # OTEL Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8002']
    metrics_path: '/metrics'

  # Config Service
  - job_name: 'config-service'
    static_configs:
      - targets: ['config-service:8004']
    metrics_path: '/metrics'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
